spring.application.name=prueba
## En mi caso cree una DB llamada PruebaTecnica con el paradigma de construccion Code-First, con un usuario llamado AbrahamRoman y una contraseña satoxehclim el cual solo tinee los permisos para acceder a la DB que previamente cree en MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/PruebaTecnica
spring.datasource.username=AbrahamRoman
spring.datasource.password=satoxehclim
spring.jpa.hibernate.ddl-auto=update