spring.application.name=prueba
## Configuración de la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/PruebaTecnica
spring.datasource.username=AbrahamRoman
spring.datasource.password=satoxehclim
spring.jpa.hibernate.ddl-auto=update
## Configuraciones para JWT
jwt.secret=783$OB#spa4&&-3KEbiylW2ZazA-LS27
jwt.expiration.time=3600000
## Encryption keys para AES-256
encryption.key=sta1$o0HlTi_huwez#p_d!ditrepr+to
encryption.salt=phAg4S-xIb3b*OtIrucREjOVlQ6R18Ir